[tool.poetry]
name = "scripts"
version = "0.1.0"
description = ""
authors = ["FranDiego"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.9.16"
click = "^8.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
